packages:
  - apps/*
  - packages/*
  - tests

catalog:
  zod: ^3.22.2
  axios: ^1.10.0
  dotenv: ^17.2.2
  date-fns: ^4.1.0
  typescript: ^5.9.2
  eslint: ^9.25.1
  prettier: ^3.2.5
  jsonwebtoken: ^9.0.2
  "@types/node": ^22
  "@types/jsonwebtoken": ^9.0.10

catalogs:
  react19:
    "@types/react": ^19.1.12
    "@types/react-dom": ^19.1.9
    react: 19.1.0
    react-dom: 19.1.0
